### ISSUE TITLE
Installing a non-pip python module

### ISSUE THREAD

**Issue by AlonDaks** [berkeley-stat159/project-lambda#25]
I plan on using a non-pip python module called PyMVPA (http://www.pymvpa.org/installation.html). I was able to successfully install this package on my mac by following the OS X install instructions. 

To ensure that this installation is reproducible, I plan on adding the install to our configuration script. To make sure I do this correctly, what OS will you be grading on? If you are using Debian, then will aptitude be a command we can assume exists?

**Comment by jarrodmillman** [comment]
You are welcome to use pymvpa.  A wheel is being built for pymvpa2 version 2.3.1 as we speak, so you should be able to add a line like:

  pymvpa2>=2.3.1

to your `requirements.txt` file (it may be a few minutes more before the wheel is publicly accessible).  This will let travis-ci install version 2.3.1 when it runs your tests.  I will contact the pymvpa folks to find out why they haven't updated the PyPI version since 2.3.1:

  https://pypi.python.org/pypi/pymvpa2/2.3.1

(I have a 2.4.0 wheel on my computer, so I will be running the latest version when I run `pip install -r requirements.txt`.)  Let me know if you need a new version than 2.3.1 and I can take care of it before the pymvpa folks update PyPI.  Otherwise, I will try to get the pymvpa folks to update PyPI first.

**Comment by jarrodmillman** [comment]
It turns out the tarball on PyPI is incorrect, so we will put 2.4.0 on the scipy wheelhouse anyway.  So just add something like

  pymvpa2>=2.4.0

to your `requirements.txt` file.  It will take sometime before it is finished building, though.

**Comment by jarrodmillman** [comment]
PyMVPA 2.4.0 for Python 2.7 is now available here
  `http://travis-wheels.scikit-image.org/pymvpa2-2.4.0-cp27-none-linux_x86_64.whl`
and travisci will find it if you add

  `pymvpa2>=2.4.0`

to your `requirements.txt` file.  There is an issue with building on Python 3, which I've reported to Yarik (one of the pymvpa developers) and awaiting a response.  I will update you when the issue is resolved.

**Comment by AlonDaks** [comment]
Thank you for the very swift follow up Jarrod! It's great to have it managed underpip. I'll close the issue when we resolve the python3 concern.
