### ISSUE TITLE
t-test or F-test?

### ISSUE THREAD

**Issue by lisaannyu** [berkeley-stat159/project-lambda#35]
@matthew-brett @jarrodmillman 

Hi Jarrod and Matthew,
We are the Forrest Gump group and I have 2 clarification questions.

Our design matrix has 5 columns:
- Scene time: Day/Night
- Scene location: Interior/Exterior
- Sentiment: Positive/Negative/Neutral
- Linear drift
- Column of ones

1) Do we need to dummy code the sentiment column into 3 separate columns, one for a positive scene, one for a negative scene, one for a neutral scene?  Then, we would use a couple contrasts comparing positive scenes to all others, and perhaps emotionally charged scenes to neutral scenes?
2) In the "Introduction to the general linear model" notes (http://www.jarrodmillman.com/rcsds/lectures/glm_intro.html), you run a t-test on the slope to test if it is significantly different from 0.  
In our case, can we also run a t-test on each of the columns of the design matrix that is interesting to us?  Or do we need to run an F-test comparing the model with the Day/Night, linear drift, and column of ones regressors to the model with just the linear drift and column of ones regressors?  Do the beta estimates account for the variance due to the intercept and linear drift, allowing us to run a t-test on just our beta estimate of interest?

Thank you!

**Comment by matthew-brett** [comment]
@jbpoline - do you want to comment here?

**Comment by matthew-brett** [comment]
For the sentiment column, it would be more flexible to code these into 3 separate columns and use contrasts, as you suggest.

You can run t-tests on the individual columns.   It turns out that, when doing the t-test, the variance term in the denominator allows for the covariance of the regressors, so yes, the t test tests for the unique contribution of the regressor of interest, or difference between the regressors if you are doing a contrast.

You could also do an F test where your question would be - does the full model explain more variance than expected by chance, over and above the reduced model.    For example you might do an F test to test whether adding the three columns for the different levels of sentiment explains more variance than just the model with other terms in it, such as the linear drift and the intercept.    JB may also like to comment - he is the real expert.

**Comment by matthew-brett** [comment]
OK to close?

**Comment by AlonDaks** [comment]
Yes -- we went with the t-test
