### ISSUE TITLE
Gaussian Filtering

### ISSUE THREAD

**Issue by AlonDaks** [berkeley-stat159/project-lambda#63]
Hi @matthew-brett 

I'm working on doing gaussian smoothing as we discussed in OH. I was wondering if I need to handle the fact that not all values in my 3D volume correspond to voxels in the brain. I presume that the 0 values in my 3D volume are coming for those voxel. If I'm using scipy.ndimage.filters.gaussian_filter on the 3D volume, would smoothed values on the boundary of the brain be incorrect since they are averaging zeros into them from outside the brain? 

What are your thoughts and suggestions?

Thanks,
Alon

**Comment by AlonDaks** [comment]
@jarrodmillman  or @rossbar Do you have any thoughts about this?

**Comment by rossbar** [comment]
One thing you could do is take the values that correspond to the edges of the brain in the image and expand them to the neighboring voxels. This technique is called "padding" the signal and would prevent the smoothing function from incorporating a bunch of non-signal voxels with signal voxels in the convolution. However, an approach like this may be difficult to implement, especially with so little time.

A simpler approach might be to run gaussian filters with several different widths over the data; one with a wider width for the brain and one with a much tighter width (or with the 'truncate' value set to a much lower value like 1 std dev instead of the default 4). For voxels that are in the interior of the brain, you can use the one set of smoothed values, and for voxels nearer the edge, you could use the results of the truncated filter. 

In the end, it may also be possible for you to justify just using a single filter and including caveats about the edge pixels. Given the width of your gaussian kernel, you should have some idea of how far in from the edge of the brain voxels will be effected by convolving with non-signal voxels. If this "edge region" is small and not expected to contain significant brain activity anyways, you could potentially justify ignoring results from this region.

**Comment by matthew-brett** [comment]
Sorry to be slow to get back to you.   It's a good question, and I agree with Ross' answer.

In practice, most brain imaging studies ignore this problem, and you're welcome to do the same, raising this as a problem, as Ross suggests.

I also think that you should be careful not to spend too much time on this, so close to the project deadline.

One approach that people have used to solve this problem, is extract the signal corresponding to the gray matter, on the outside of the brain, and then smooth the values on the 2D surface - here's an example : 

```
@article {HBM:HBM1005,
author = {Andrade, Alexandre and Kherif, Ferath and Mangin, Jean-François and Worsley, Keith J. and Paradis, Anne-Lise and Simon, Olivier and Dehaene, Stanislas and Le Bihan, Denis and Poline, Jean-Baptiste},
title = {Detection of fMRI activation using Cortical Surface Mapping},
journal = {Human Brain Mapping},
volume = {12},
number = {2},
publisher = {John Wiley & Sons, Inc.},
issn = {1097-0193},
url = {http://dx.doi.org/10.1002/1097-0193(200102)12:2<79::AID-HBM1005>3.0.CO;2-I},
doi = {10.1002/1097-0193(200102)12:2<79::AID-HBM1005>3.0.CO;2-I},
pages = {79--93},
keywords = {statistical analysis, cortical surface, spatial smoothing, fMRI, methodology},
year = {2001},
}
```
