### ISSUE TITLE
Brain Mask Cutoff

### ISSUE THREAD

**Issue by AlonDaks** [berkeley-stat159/project-lambda#75]
Hi @matthew-brett 
I am following your instructions for deriving a brain mask from these lecture notes: http://www.jarrodmillman.com/rcsds/lectures/modeling_noise.html. However our histogram is bimodal. What should we do in this case? Should we set our threshold at the trough between modes or does this mean that we did the analysis (histogram generation) wrong?

![subj_1_vol_mean_histogram](https://cloud.githubusercontent.com/assets/1865239/11764700/af9ebb06-a0ef-11e5-8ae2-4ca5f6a1b0d6.png)

**Comment by matthew-brett** [comment]
No - that's right - my histogram is also bimodal but the second peak is harder to see, I guess because of the huge density of 0 values in my image.  Maybe your image has fewer zeros because it's preprocessed, and includes less space outside the brain?

In any case, yes, you go for the trough - so around 150 in this case.

**Comment by AlonDaks** [comment]
Thank you for reviewing this. Yes, my image does look like there is fewer space outside the brain and it has been preprocessed. 

I will go with 160.
