### ISSUE TITLE
EC2 Instance Type

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-lambda#93]
Which EC2 instance type were you running on? The NE cluster is pretty jammed up with the nuclear engineering final projects so I may need to use a different service. It looks like the r3.4xlarge is the cheapest one that meets your specs

**Comment by AlonDaks** [comment]
I did the original project on a r3.4xlarge machine located in oregon (I don't think location is that important since we're not serving users). 

Note that to get python requirements to work I had to use a virtualenv. Please let me know if you get errors when dealing with installing dependencies or python things on amazon because I debugged a lot of strange things that didn't show up on my mac.

**Comment by rossbar** [comment]
Okay, the NE cluster has cleared up with all the students having finished their final projects. I'm running on a high-memory node and have adequate storage. What was your runtime like on EC2?

**Comment by AlonDaks** [comment]
It didn't take very long on EC2. 

The download is a function of your network connection. wget provides realtime feedback for how long a download is taking (it downloads 40 files of similar form).

The preprocess step takes the longest. It took around an hour. It outputs print statements with file names that have been generate, so expect to see the first print statement within 10 minutes of running.

Reproduction step takes about an hour.

Cross validation takes about 40 minutes.


All of these numbers of rough estimates. It's something that should finish within a few hours I'd say.

**Comment by rossbar** [comment]
Okay because I'm on hour 9 and haven't gotten through the preprocessing yet it appears... I will try again with a different node.

**Comment by AlonDaks** [comment]
How many file outputs do you see?

**Comment by rossbar** [comment]
what do you mean? things printed by the preprocess.py script or files stored somewhere on disk?

**Comment by rossbar** [comment]
in the `data/processed` dir I've gotten up to sub6_rcds_smoothed_8mm.npy

**Comment by rossbar** [comment]
Contents of the `data/processed/` directory:

```
sub1_rcds.npy                   sub3_rcds_smoothed_8_mm_2d.npy
sub1_rcds_smoothed_4_mm_2d.npy  sub3_rcds_smoothed_8_mm.npy
sub1_rcds_smoothed_4_mm.npy     sub5_rcds.npy
sub1_rcds_smoothed_8_mm_2d.npy  sub5_rcds_smoothed_8_mm_2d.npy
sub1_rcds_smoothed_8_mm.npy     sub5_rcds_smoothed_8_mm.npy
sub2_rcds.npy                   sub6_rcds.npy
sub2_rcds_smoothed_8_mm_2d.npy  sub6_rcds_smoothed_8_mm_2d.npy
sub2_rcds_smoothed_8_mm.npy     sub6_rcds_smoothed_8_mm.npy
sub3_rcds.npy
```

**Comment by AlonDaks** [comment]
You are almost done then. It should have printed each of those names to the shell as each of those files were finished being written

**Comment by rossbar** [comment]
I'm using a batch scheduler and I probably have stdout redirecting somewhere so I didn't see them

**Comment by rossbar** [comment]
Were you using all the cores on the EC2 node?

**Comment by AlonDaks** [comment]
Those are actually all of the files you need. I'm not sure why the script didn't exit

**Comment by AlonDaks** [comment]
I didn't explicitly parallelize on EC2. I think numpy by default does not use multiple cores. The part of the project that will use as many cores as possible is the cross-validation and validation training for our RF models.

**Comment by rossbar** [comment]
What should the `figures/` dir have in it after a successful analysis run?

**Comment by AlonDaks** [comment]
I updated the readme to get ride of the make all-analysis instruction (since i removed that a while ago). It's best if you do the analysis step by step. 

After running make eda you should get:

/figures/sim_inter_run_correlations.txt
/figures/sim_inter_run.png
/figures/subj_1_vol_mean_histogram.png
/figures/brain_mask.png
/figures/subj1_vol_rms_diff.png

after make reproduction
**In data/processed**
/data/processed/sub1_sub2_correlation.npy
/data/processed/sub1_sub3_correlation.npy
/data/processed/sub1_sub5_correlation.npy
/data/processed/sub1_sub6_correlation.npy
/data/processed/sub2_sub3_correlation.npy
/data/processed/sub2_sub5_correlation.npy
/data/processed/sub2_sub6_correlation.npy
/data/processed/sub3_sub5_correlation.npy
/data/processed/sub3_sub6_correlation.npy
/data/processed/sub5_sub6_correlation.npy
**in figures**
/figures/mean_correlation_histogram.png
/figures/pooled_correlation_histogram.png
/figures/mean_correlation_percentiles.txt
/figures/pooled_correlation_percentiles.txt
/figures/correlated_brain_light.png
/figures/correlated_brain_dark.png

after make classification-cross-validate
/figures/rf_cross_validated_accuracies.txt

after make classification-validation
/figures/validation_accuracy.txt

**Comment by rossbar** [comment]
Thanks for all the extra info. I was able to run it on the NE cluster. For whatever reason the analysis was taking a really long time; though I know this was the node's fault not your guys' code. Anyways, everything ran without error at first pass :+1:
